my_dbt_project:
  target: local
  outputs:
    # Local development with Docker Compose
    local:
      type: postgres
      host: localhost
      port: 5432
      user: dbt_user
      password: dbt_password
      dbname: analytics
      schema: public
      threads: 4
    
    # Dev environment in K8s (accessed from GitHub Actions)
    dev:
      type: postgres
      host: "{{ env_var('DEV_DB_HOST') }}"
      port: 5432
      user: dbt_user
      password: "{{ env_var('DEV_DB_PASSWORD') }}"
      dbname: analytics
      schema: public
      threads: 4
    
    # Staging environment in K8s
    staging:
      type: postgres
      host: "{{ env_var('STAGING_DB_HOST') }}"
      port: 5432
      user: dbt_user
      password: "{{ env_var('STAGING_DB_PASSWORD') }}"
      dbname: analytics
      schema: public
      threads: 4
    
    # Production environment in K8s
    prod:
      type: postgres
      host: "{{ env_var('PROD_DB_HOST') }}"
      port: 5432
      user: dbt_user
      password: "{{ env_var('PROD_DB_PASSWORD') }}"
      dbname: analytics
      schema: public
      threads: 8
