my_dbt_project:
  target: local  # Default to local DuckDB for fast development
  
  outputs:
    # Local DuckDB - fast iteration, no external connection
   local:
    type: duckdb
    path: /tmp/dbt.duckdb
    database: main
    schema: main
    threads: 4
    
    # Personal Databricks dev schema - for validation before PR
    dev_databricks:
      type: databricks
      host: purplewave.cloud.databricks.com
      http_path: /sql/1.0/warehouses/your_warehouse_path_here
      schema: "dev_{{ env_var('USER', 'default') }}"
      token: "{{ env_var('DBX_DEV_TOKEN', 'dummy') }}"
      threads: 4
    
    # CI testing - used by GitHub Actions (future)
    ci:
      type: databricks
      host: purplewave.cloud.databricks.com
      http_path: /sql/1.0/warehouses/your_warehouse_path_here
      schema: ci_testing
      token: "{{ env_var('DBX_CI_TOKEN', 'dummy') }}"
      threads: 4
    
    # Production - used by Kubernetes (future)
    prod:
      type: databricks
      host: purplewave.cloud.databricks.com
      http_path: /sql/1.0/warehouses/your_warehouse_path_here
      schema: production
      token: "{{ env_var('DBX_PROD_TOKEN', 'dummy') }}"
      threads: 8