my_dbt_project:
  target: local
  outputs:
    local:
      type: postgres
      host: localhost
      port: 5434
      user: dbt_user
      password: dbt_password
      dbname: dbt_dev
      schema: public
      threads: 4
    
    dev:
      type: postgres
      host: localhost
      port: 5436  # Port-forward to K8s dev
      user: dbt_user
      password: dbt_password
      dbname: dbt_dev
      schema: public
      threads: 4
    
    staging:
      type: postgres
      host: localhost
      port: 5437  # Port-forward to K8s staging
      user: dbt_user
      password: dbt_password
      dbname: dbt_dev
      schema: public
      threads: 4
    
    prod:
      type: postgres
      host: localhost
      port: 5438  # Port-forward to K8s prod
      user: dbt_user
      password: dbt_password
      dbname: dbt_dev
      schema: public
      threads: 8