my_dbt_project:
  target: local
  outputs:
    local:
      type: postgres
      host: localhost
      port: 5432
      user: dbt_user
      password: dbt_password
      dbname: analytics
      schema: public
      threads: 4
    
    dev:
      type: postgres
      host: "{{ env_var('DEV_DB_HOST') }}"
      port: 5432
      user: dbt_user
      password: "{{ env_var('DEV_DB_PASSWORD') }}"
      dbname: dbt_dev
      schema: public
      threads: 4
    
    staging:
      type: postgres
      host: "{{ env_var('STAGING_DB_HOST') }}"
      port: 5432
      user: dbt_user
      password: "{{ env_var('STAGING_DB_PASSWORD') }}"
      dbname: dbt_dev
      schema: public
      threads: 4
    
    prod:
      type: postgres
      host: "{{ env_var('PROD_DB_HOST') }}"
      port: 5432
      user: dbt_user
      password: "{{ env_var('PROD_DB_PASSWORD') }}"
      dbname: dbt_dev
      schema: public
      threads: 8